version: '3.1'

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
#    command: ["./wait-for-it.sh"]
#    volumes:
#      - "./docker/mysql/wait-for-it.sh:/wait-for-it.sh"
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./docker/frontend/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - 80:80
    command: /bin/bash -c "envsubst '$$BACKEND_HOST $$BACKEND_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  db:
    container_name: blog_db
    image: mysql
    restart: always
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"