version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - fredrsf

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - fredrsf
    #command: /bin/bash -c "envsubst '$$BACKEND_HOST $$BACKEND_PORT' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    networks:
      - nginx_net
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - frontend

networks:
  fredrsf:
    name: fredrsf