version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/frontend/fredrsf.conf:/etc/nginx/conf.d/fredrsf.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - fredrsf