version: '3.1'

services:

  db:
    container_name: blog_db
    image: mysql
    restart: always
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"