version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./docker/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/frontend/fredrsf.conf:/etc/nginx/sites-enabled/fredrsf.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    network_mode: "host"